version: "3"
services:
  aria:
    build: .
    restart: always
    hostname: aria
    user: root
    ports:
     - "8082:80"
     - "6800:6800"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/data
      - ./aria2.conf:/aria2.conf
